# Generated by Django 5.1.5 on 2025-08-25 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='owner',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='read_count',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='reading_time',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='state',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
