# Generated by Django 5.1.2 on 2025-01-13 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JMapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('end_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='JMapp.station')),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='JMapp.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JMapp.train')),
            ],
        ),
    ]
