# Generated by Django 5.1.2 on 2025-01-13 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JMapp', '0002_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train_route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_date', models.DateField()),
                ('Train_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JMapp.train')),
                ('station', models.ManyToManyField(to='JMapp.station')),
            ],
        ),
    ]
